version: '3.8'

services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_SHOW_SQL: "true"
    volumes:
      - ./eventify-backend/src:/app/src
      - ./eventify-backend/build:/app/build

  frontend:
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./booking-ui/src:/app/src
      - /app/node_modules